### ISSUE TITLE
This isn't really a feature request but...

### ISSUE THREAD

**Issue by Joalor64GH** [l1ttleO/ProjectFNF#33] opened 2022-04-08 12:32 UTC
### What feature do you want to get added on the **base** engine?

Could you please make this repository a public template?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by l1ttleO** [comment] 2022-04-08 14:33
Duplicate of #22, but sure, I'll make it a template

**Closed by l1ttleO** 2022-04-08 14:33 UTC
Labels: status: duplicate, type: enhancement
